# site settings
title: Transcistada
subtitle: identidades
email: contato.transcistada@gmail.com
description: Uma performance multimídia que abarca a diversidade ao falar da intersecção entre diversas formas opressão sobre os corpos, que incluem gênero, etnia, forma, classe social dando espaço a potências de (re)existência.
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone: +55 11 959902448

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: https://facebook.com/transcistada
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/transcistada
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

plugins:
  - jekyll-gallery-generator

sass:
  style: compressed
